# -*- coding: utf-8 -*-
"""Copy of Dino/Monai.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SC5VhQ3qoNXdlV2bSxscnM8RTHqUqVDU
"""

#install package
!pip -q install monai nibabel torch torchvision transformers

import nibabel as nib

img = nib.load("/content/t1.nii")
data = img.get_fdata()

print(data.shape)

#debug1
import os
os.listdir("/content")

#debug2
import os
os.listdir("/content")

#visualization

import matplotlib.pyplot as plt


mid = data.shape[2] // 2

plt.imshow(data[:, :, mid], cmap="gray")
plt.title("Middle slice")
plt.axis("off")
plt.show()

import torch
import numpy as np

# normalize
data_norm = (data - data.min()) / (data.max() - data.min() + 1e-8)

# add channel
vol = torch.tensor(data_norm).unsqueeze(0).float()  # (1, H, W, D)

print(vol.shape)

"""DINO Development"""

!pip -q install transformers torch torchvision

import numpy as np
import torch
from transformers import AutoImageProcessor, AutoModel

# data is your numpy array from nibabel: shape (H, W, D)
z = data.shape[2] // 2
slice_2d = data[:, :, z]  # (H, W)
print("Slice shape:", slice_2d.shape, "z =", z)

# normalize to 0..1
s = slice_2d.astype(np.float32)
s = (s - s.min()) / (s.max() - s.min() + 1e-8)

# make 3-channel (H, W, 3)
img = np.stack([s, s, s], axis=-1)
print("DINO image shape:", img.shape)

processor = AutoImageProcessor.from_pretrained("facebook/dinov2-base")
model = AutoModel.from_pretrained("facebook/dinov2-base")
model.eval()

inputs = processor(images=img, return_tensors="pt")

with torch.no_grad():
    outputs = model(**inputs)

tokens = outputs.last_hidden_state  # (B, seq_len, hidden)
print("Tokens:", tokens.shape)

emb_mean = tokens[:, 1:].mean(dim=1)  # (1, hidden)
print("Mean-pooled embedding:", emb_mean.shape)

def dino_embed_slice(slice_2d, processor, model):
    s = slice_2d.astype(np.float32)
    s = (s - s.min()) / (s.max() - s.min() + 1e-8)
    img = np.stack([s, s, s], axis=-1)

    inputs = processor(images=img, return_tensors="pt")
    with torch.no_grad():
        out = model(**inputs).last_hidden_state
    return out[:, 1:].mean(dim=1).squeeze(0)  # (hidden,)

zs = np.linspace(0, data.shape[2]-1, 9).astype(int)  # 9 slices
embs = [dino_embed_slice(data[:, :, z], processor, model) for z in zs]
emb_vol = torch.stack(embs).mean(dim=0)  # (hidden,)

print("Volume embedding from 9 slices:", emb_vol.shape)
print("Slices used:", zs)

#using all slices of MRI
import torch
import numpy as np
import torch.nn.functional as F

def dino_embed_slice_meanpool(slice_2d, processor, model):
    s = slice_2d.astype(np.float32)
    s = (s - s.min()) / (s.max() - s.min() + 1e-8)  # 0..1
    img = np.stack([s, s, s], axis=-1)              # (H, W, 3)

    inputs = processor(images=img, return_tensors="pt")
    # keep on CPU unless you explicitly move model to GPU
    with torch.no_grad():
        tokens = model(**inputs).last_hidden_state   # (1, seq, hidden)

    # mean pool patch tokens (drop CLS token at index 0)
    emb = tokens[:, 1:].mean(dim=1).squeeze(0)       # (hidden,)
    return emb

# --- Embed ALL slices ---
embs = []
D = data.shape[2]

for z in range(D):
    emb = dino_embed_slice_meanpool(data[:, :, z], processor, model)
    embs.append(emb)

embs = torch.stack(embs, dim=0)   # (D, 768)
emb_vol_all = embs.mean(dim=0)    # (768,)

print("All-slice volume embedding:", emb_vol_all.shape)
print("Slices used:", D)

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
model = model.to(device)

def dino_embed_slice_meanpool(slice_2d, processor, model, device):
    s = slice_2d.astype(np.float32)
    s = (s - s.min()) / (s.max() - s.min() + 1e-8)
    img = np.stack([s, s, s], axis=-1)

    inputs = processor(images=img, return_tensors="pt").to(device)
    with torch.no_grad():
        tokens = model(**inputs).last_hidden_state
    return tokens[:, 1:].mean(dim=1).squeeze(0).detach().cpu()

embs = []
D = data.shape[2]
for z in range(D):
    embs.append(dino_embed_slice_meanpool(data[:, :, z], processor, model, device))

embs = torch.stack(embs)
emb_vol_all = embs.mean(dim=0)

print("All-slice volume embedding:", emb_vol_all.shape)

#comparing 9 slice to all slice

cos = F.cosine_similarity(emb_vol, emb_vol_all, dim=0)  # emb_vol from your 9-slice run
print("Cosine similarity (9-slice vs all-slice):", float(cos))

"""MONAI Development"""

pip -q install "monai>=1.5.1" nibabel

import torch
import nibabel as nib
import numpy as np
from monai.transforms import Compose, EnsureChannelFirst, ScaleIntensity, ResizeWithPadOrCrop

path = "/content/t1.nii"  # adjust if needed

nii = nib.load(path)
vol = nii.get_fdata().astype(np.float32)  # (H,W,D)

tx = Compose([
    EnsureChannelFirst(channel_dim="no_channel"),  # -> (1,H,W,D)
    ScaleIntensity(),                              # simple normalize
    ResizeWithPadOrCrop(spatial_size=(128,128,128))
])

x = tx(vol)                         # numpy
x = torch.tensor(x).unsqueeze(0)    # -> (B=1, C=1, 128,128,128)
print("input:", x.shape)

from monai.networks.nets import MaskedAutoEncoderViT

device = "cuda" if torch.cuda.is_available() else "cpu"

mae = MaskedAutoEncoderViT(
    in_channels=1,
    img_size=(128,128,128),
    patch_size=(16,16,16),   # 128 divisible by 16 ✅
    spatial_dims=3,
    masking_ratio=0.75
).to(device).eval()

with torch.no_grad():
    pred, mask = mae(x.to(device))

print("pred patches:", pred.shape)   # (B, num_patches, patch_volume*channels)
print("mask:", mask.shape)          # (B, num_patches)
print("masked %:", mask.float().mean().item())

import torch.nn.functional as F

def mae_cls_embedding(mae, x):
    # run encoder with NO masking so embedding is stable
    tokens = mae.patch_embedding(x)                       # (B, N, hidden)
    x_masked, idx, mask = mae._masking(tokens, masking_ratio=0.0)
    cls = mae.cls_token.expand(x.shape[0], -1, -1)
    enc_in = torch.cat((cls, x_masked), dim=1)            # (B, 1+N, hidden)
    enc_out = mae.blocks(enc_in)                          # (B, 1+N, hidden)
    return enc_out[:, 0, :]                               # (B, hidden)

with torch.no_grad():
    emb = mae_cls_embedding(mae, x.to(device)).squeeze(0).cpu()

print("MAE CLS embedding:", emb.shape)  # typically torch.Size([768])

"""START TESTING THE 10 DATA POINTS"""

ZIP_DIR = "/content"

import os
import re
import glob
import pandas as pd

NII_DIR = "/content"   # change if your files are somewhere else

nii_files = sorted(
    glob.glob(os.path.join(NII_DIR, "*.nii")) +
    glob.glob(os.path.join(NII_DIR, "*.nii.gz"))
)

print("Found files:", len(nii_files))
for f in nii_files:
    print(os.path.basename(f))

records = []

for path in nii_files:
    name = os.path.basename(path)

    # control if filename looks like d1.nii, d2.nii, etc.
    if re.fullmatch(r"d\d+\.nii(\.gz)?", name.lower()):
        label = 0
        group = "control"
    else:
        label = 1
        group = "dementia"

    records.append({
        "file_name": name,
        "nifti_path": path,
        "label": label,
        "group": group
    })

df_files = pd.DataFrame(records)
print(df_files)

!pip -q install monai nibabel torch torchvision transformers scikit-learn pandas

import numpy as np
import torch
import nibabel as nib

from transformers import AutoImageProcessor, AutoModel
from monai.transforms import Compose, EnsureChannelFirst, ScaleIntensity, ResizeWithPadOrCrop
from monai.networks.nets import MaskedAutoEncoderViT

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print("Device:", device)

# DINO
processor = AutoImageProcessor.from_pretrained("facebook/dinov2-base")
dino_model = AutoModel.from_pretrained("facebook/dinov2-base").to(device)
dino_model.eval()

# MONAI 3D-MAE
mae_model = MaskedAutoEncoderViT(
    in_channels=1,
    img_size=(128, 128, 128),
    patch_size=(16, 16, 16),
    spatial_dims=3,
    masking_ratio=0.75
).to(device)
mae_model.eval()

# ---------- DINO ----------
def dino_embed_slice_meanpool(slice_2d, processor, model, device):
    s = slice_2d.astype(np.float32)
    s = (s - s.min()) / (s.max() - s.min() + 1e-8)
    img = np.stack([s, s, s], axis=-1)   # grayscale -> 3-channel

    inputs = processor(images=img, return_tensors="pt").to(device)

    with torch.no_grad():
        tokens = model(**inputs).last_hidden_state

    emb = tokens[:, 1:].mean(dim=1).squeeze(0).detach().cpu()
    return emb

def get_dino_volume_embedding(volume, processor, model, device, n_slices=9):
    zs = np.linspace(0, volume.shape[2] - 1, n_slices).astype(int)
    embs = [dino_embed_slice_meanpool(volume[:, :, z], processor, model, device) for z in zs]
    return torch.stack(embs).mean(dim=0)


# ---------- MONAI 3D-MAE ----------
mae_transform = Compose([
    EnsureChannelFirst(channel_dim="no_channel"),
    ScaleIntensity(),
    ResizeWithPadOrCrop(spatial_size=(128, 128, 128))
])

def mae_cls_embedding(mae, x):
    with torch.no_grad():
        tokens = mae.patch_embedding(x)
        x_masked, _, _ = mae._masking(tokens, masking_ratio=0.0)
        cls = mae.cls_token.expand(x.shape[0], -1, -1)
        enc_in = torch.cat((cls, x_masked), dim=1)
        enc_out = mae.blocks(enc_in)
        return enc_out[:, 0, :]

def get_mae_volume_embedding(volume, mae_model, device):
    x = mae_transform(volume).astype(np.float32)
    x = torch.tensor(x).unsqueeze(0).to(device)   # (1,1,128,128,128)

    with torch.no_grad():
        emb = mae_cls_embedding(mae_model, x).squeeze(0).cpu()

    return emb

dino_embeddings = []
mae_embeddings = []

for i, row in df_files.iterrows():
    path = row["nifti_path"]
    name = row["file_name"]

    print(f"[{i+1}/{len(df_files)}] Processing: {name}")

    img = nib.load(path)
    vol = img.get_fdata().astype(np.float32)

    dino_emb = get_dino_volume_embedding(vol, processor, dino_model, device, n_slices=9)
    mae_emb = get_mae_volume_embedding(vol, mae_model, device)

    dino_embeddings.append(dino_emb.numpy())
    mae_embeddings.append(mae_emb.numpy())

df_files["dino_embedding"] = dino_embeddings
df_files["mae_embedding"] = mae_embeddings

print("\nDone.")
print(df_files[["file_name", "group", "label"]])

import numpy as np
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import StratifiedKFold, cross_val_score

X_dino = np.stack(df_files["dino_embedding"].values)
y = df_files["label"].values

cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)

clf_dino = make_pipeline(
    StandardScaler(),
    LogisticRegression(max_iter=2000)
)

acc_scores = cross_val_score(clf_dino, X_dino, y, cv=cv, scoring="accuracy")
auc_scores = cross_val_score(clf_dino, X_dino, y, cv=cv, scoring="roc_auc")

print("DINO Accuracy scores:", acc_scores)
print("DINO Mean Accuracy:", acc_scores.mean())
print("DINO AUC scores:", auc_scores)
print("DINO Mean AUC:", auc_scores.mean())

X_mae = np.stack(df_files["mae_embedding"].values)
y = df_files["label"].values

clf_mae = make_pipeline(
    StandardScaler(),
    LogisticRegression(max_iter=2000)
)

acc_scores = cross_val_score(clf_mae, X_mae, y, cv=cv, scoring="accuracy")
auc_scores = cross_val_score(clf_mae, X_mae, y, cv=cv, scoring="roc_auc")

print("MAE Accuracy scores:", acc_scores)
print("MAE Mean Accuracy:", acc_scores.mean())
print("MAE AUC scores:", auc_scores)
print("MAE Mean AUC:", auc_scores.mean())

df_files.to_pickle("/content/mri_embedding_results.pkl")
print("Saved: /content/mri_embedding_results.pkl")

X_combined = np.concatenate([X_dino, X_mae], axis=1).astype(np.float32)
print("X_combined shape:", X_combined.shape)   # (N, 1536)

import torch
import torch.nn as nn

class EmbeddingMLP(nn.Module):
    def __init__(self, input_dim):
        super().__init__()
        self.net = nn.Sequential(
            nn.Linear(input_dim, 128),
            nn.ReLU(),
            nn.Dropout(0.3),

            nn.Linear(128, 32),
            nn.ReLU(),
            nn.Dropout(0.2),

            nn.Linear(32, 1)   # one output for binary classification
        )

    def forward(self, x):
        return self.net(x)

import numpy as np
import torch
from torch.utils.data import Dataset, DataLoader
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score, roc_auc_score, classification_report

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print("Device:", device)

class EmbeddingDataset(Dataset):
    def __init__(self, X, y):
        self.X = torch.tensor(X, dtype=torch.float32)
        self.y = torch.tensor(y, dtype=torch.float32).unsqueeze(1)  # (N,1)

    def __len__(self):
        return len(self.X)

    def __getitem__(self, idx):
        return self.X[idx], self.y[idx]

X_dino = np.stack(df_files["dino_embedding"].values).astype(np.float32)
X_mae = np.stack(df_files["mae_embedding"].values).astype(np.float32)
X = np.concatenate([X_dino, X_mae], axis=1).astype(np.float32)
y = df_files["label"].values.astype(np.float32)

X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    stratify=y,
    random_state=42
)

scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

train_dataset = EmbeddingDataset(X_train, y_train)
test_dataset = EmbeddingDataset(X_test, y_test)

train_loader = DataLoader(train_dataset, batch_size=4, shuffle=True)
test_loader = DataLoader(test_dataset, batch_size=4, shuffle=False)

input_dim = X_train.shape[1]
model = EmbeddingMLP(input_dim=input_dim).to(device)

criterion = nn.BCEWithLogitsLoss()
optimizer = torch.optim.Adam(model.parameters(), lr=1e-3, weight_decay=1e-4)

num_epochs = 50

for epoch in range(num_epochs):
    model.train()
    total_loss = 0.0

    for xb, yb in train_loader:
        xb, yb = xb.to(device), yb.to(device)

        optimizer.zero_grad()
        logits = model(xb)
        loss = criterion(logits, yb)
        loss.backward()
        optimizer.step()

        total_loss += loss.item()

    avg_loss = total_loss / len(train_loader)

    if (epoch + 1) % 10 == 0:
        print(f"Epoch {epoch+1}/{num_epochs}, Loss: {avg_loss:.4f}")

model.eval()
all_probs = []
all_preds = []
all_true = []

with torch.no_grad():
    for xb, yb in test_loader:
        xb = xb.to(device)
        logits = model(xb)

        probs = torch.sigmoid(logits).cpu().numpy().flatten()
        preds = (probs >= 0.5).astype(int)

        all_probs.extend(probs)
        all_preds.extend(preds)
        all_true.extend(yb.numpy().flatten())

acc = accuracy_score(all_true, all_preds)

# roc_auc_score needs both classes present in test set
if len(np.unique(all_true)) > 1:
    auc = roc_auc_score(all_true, all_probs)
else:
    auc = float("nan")

print("Test Accuracy:", acc)
print("Test AUC:", auc)
print(classification_report(all_true, all_preds, digits=4))

class EmbeddingDataset(Dataset):
    def __init__(self, X, y):
        self.X = torch.tensor(X, dtype=torch.float32)
        self.y = torch.tensor(y, dtype=torch.float32).unsqueeze(1)

    def __len__(self):
        return len(self.X)

    def __getitem__(self, idx):
        return self.X[idx], self.y[idx]


class EmbeddingMLP(nn.Module):
    def __init__(self, input_dim):
        super().__init__()
        self.net = nn.Sequential(
            nn.Linear(input_dim, 128),
            nn.ReLU(),
            nn.Dropout(0.3),
            nn.Linear(128, 32),
            nn.ReLU(),
            nn.Dropout(0.2),
            nn.Linear(32, 1)
        )

    def forward(self, x):
        return self.net(x)

#X = np.stack(df_files["dino_embedding"].values).astype(np.float32)
#y = df_files["label"].values.astype(np.float32)

# For MAE instead:
# X = np.stack(df_files["mae_embedding"].values).astype(np.float32)

# For combined:
X_dino = np.stack(df_files["dino_embedding"].values).astype(np.float32)
X_mae = np.stack(df_files["mae_embedding"].values).astype(np.float32)
X = np.concatenate([X_dino, X_mae], axis=1).astype(np.float32)

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)

acc_scores = []
auc_scores = []

for fold, (train_idx, test_idx) in enumerate(cv.split(X, y), start=1):
    print(f"\n===== Fold {fold} =====")

    X_train, X_test = X[train_idx], X[test_idx]
    y_train, y_test = y[train_idx], y[test_idx]

    # scale inside each fold
    scaler = StandardScaler()
    X_train = scaler.fit_transform(X_train)
    X_test = scaler.transform(X_test)

    train_dataset = EmbeddingDataset(X_train, y_train)
    test_dataset = EmbeddingDataset(X_test, y_test)

    train_loader = DataLoader(train_dataset, batch_size=4, shuffle=True)
    test_loader = DataLoader(test_dataset, batch_size=4, shuffle=False)

    model = EmbeddingMLP(input_dim=X.shape[1]).to(device)
    criterion = nn.BCEWithLogitsLoss()
    optimizer = torch.optim.Adam(model.parameters(), lr=1e-3, weight_decay=1e-4)

    num_epochs = 50

    for epoch in range(num_epochs):
        model.train()
        total_loss = 0.0

        for xb, yb in train_loader:
            xb, yb = xb.to(device), yb.to(device)

            optimizer.zero_grad()
            logits = model(xb)
            loss = criterion(logits, yb)
            loss.backward()
            optimizer.step()

            total_loss += loss.item()

    # evaluate fold
    model.eval()
    all_probs = []
    all_preds = []
    all_true = []

    with torch.no_grad():
        for xb, yb in test_loader:
            xb = xb.to(device)
            logits = model(xb)

            probs = torch.sigmoid(logits).cpu().numpy().flatten()
            preds = (probs >= 0.5).astype(int)

            all_probs.extend(probs)
            all_preds.extend(preds)
            all_true.extend(yb.numpy().flatten())

    acc = accuracy_score(all_true, all_preds)
    acc_scores.append(acc)

    if len(np.unique(all_true)) > 1:
        auc = roc_auc_score(all_true, all_probs)
        auc_scores.append(auc)
        print(f"Fold {fold} Accuracy: {acc:.4f}, AUC: {auc:.4f}")
    else:
        print(f"Fold {fold} Accuracy: {acc:.4f}, AUC: undefined")

print("\n===== Final Results =====")
print("Accuracy scores:", acc_scores)
print("Mean Accuracy:", np.mean(acc_scores))

if len(auc_scores) > 0:
    print("AUC scores:", auc_scores)
    print("Mean AUC:", np.mean(auc_scores))

X_dino = np.stack(df_files["dino_embedding"].values).astype(np.float32)
X_mae = np.stack(df_files["mae_embedding"].values).astype(np.float32)
X = np.concatenate([X_dino, X_mae], axis=1).astype(np.float32)
y = df_files["label"].values.astype(np.float32)

print(X.shape)   # should be (N, 1536)

