# -*- coding: utf-8 -*-
"""ETF_Backtesting_Algortithm.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13m42e4aV3BbmD4Uk0W9HmA4IEVtx7qbu
"""

"""
STEP 1 + 2: Pull sector ETF price data, then test candidate pairs for cointegration.

Cointegration = a statistical test that tells us whether two price series have a
*stable long-run relationship* (they tend to drift back toward each other over time)
rather than just being randomly correlated in the short term.

Run this locally: pip install yfinance statsmodels pandas numpy matplotlib
"""

import yfinance as yf
import pandas as pd
import numpy as np
from statsmodels.tsa.stattools import coint
import matplotlib.pyplot as plt

# ---------------------------------------------------------
# STEP 1: Pull data
# ---------------------------------------------------------

# Candidate pairs to test — sectors that are economically linked
CANDIDATE_PAIRS = [
    ("XLE", "XLB"),  # Energy vs Materials (both commodity-sensitive) <------ we will advance with these etf's
    ("XLF", "XLI"),  # Financials vs Industrials
    ("XLU", "XLP"),  # Utilities vs Staples (both "defensive" sectors)
    ("XLK", "XLY"),  # Tech vs Consumer Discretionary
]

# Flatten to a unique list of tickers we need to download
all_tickers = sorted(set(t for pair in CANDIDATE_PAIRS for t in pair))

print(f"Pulling 5 years of daily data for: {all_tickers}")

# yfinance downloads all tickers at once and returns a multi-column DataFrame
raw = yf.download(all_tickers, period="5y", auto_adjust=True)["Close"]

# Drop any rows with missing data (e.g. holidays where one ticker didn't trade)
prices = raw.dropna()

print(f"\nData shape: {prices.shape[0]} trading days x {prices.shape[1]} tickers")
print(prices.head())

# Save so we don't have to re-download every time we run the script
prices.to_csv("sector_etf_prices.csv")
print("\nSaved to sector_etf_prices.csv")

# ---------------------------------------------------------
# STEP 2: Test each candidate pair for cointegration
# ---------------------------------------------------------

print("\n" + "=" * 60)
print("COINTEGRATION TEST RESULTS")
print("=" * 60)

results = []

for ticker_a, ticker_b in CANDIDATE_PAIRS:
    series_a = prices[ticker_a]
    series_b = prices[ticker_b]

    # coint() returns: test statistic, p-value, critical values
    # p-value < 0.05 is the conventional cutoff for "likely cointegrated"
    score, pvalue, _ = coint(series_a, series_b)

    results.append({
        "pair": f"{ticker_a}/{ticker_b}",
        "p_value": round(pvalue, 4),
        "likely_cointegrated": pvalue < 0.05
    })

    print(f"{ticker_a}/{ticker_b}: p-value = {pvalue:.4f} "
          f"{'<-- COINTEGRATED' if pvalue < 0.05 else ''}")

results_df = pd.DataFrame(results)
print("\nSummary:")
print(results_df)

# ---------------------------------------------------------
# Plot the price ratio for each pair so you can eyeball mean reversion
# ---------------------------------------------------------

fig, axes = plt.subplots(len(CANDIDATE_PAIRS), 1, figsize=(10, 12))

for ax, (ticker_a, ticker_b) in zip(axes, CANDIDATE_PAIRS):
    ratio = prices[ticker_a] / prices[ticker_b]
    ax.plot(ratio.index, ratio.values)
    ax.axhline(ratio.mean(), color="red", linestyle="--", alpha=0.7, label="mean")
    ax.set_title(f"{ticker_a}/{ticker_b} price ratio")
    ax.legend()

plt.tight_layout()
plt.savefig("pair_ratios.png", dpi=120)
print("\nSaved ratio plots to pair_ratios.png")
plt.show()

"""
STEP 2b: Two follow-up analyses based on what we learned from the broad sector ETFs.

PART A: Rolling cointegration test on XLE/XLB
  Instead of one p-value for all 5 years, we test cointegration on a rolling window
  (e.g. the trailing 252 trading days = ~1 year) and slide it forward day by day.
  This shows us WHEN the relationship was actually reliable vs. when it broke down —
  which is exactly the kind of signal we'll need for labeling "revert vs break" later.

PART B: Test more granular pairs
  Broad sector ETFs are noisy because they average dozens of companies together.
  Same-industry single stocks or subsector ETFs often share more direct business
  drivers, so they may cointegrate more cleanly.

Run this locally: pip install yfinance statsmodels pandas numpy matplotlib
"""

import yfinance as yf
import pandas as pd
import numpy as np
from statsmodels.tsa.stattools import coint
import matplotlib.pyplot as plt

# ---------------------------------------------------------
# PART A: Rolling cointegration on XLE/XLB
# ---------------------------------------------------------

print("Loading previously saved price data...")
prices = pd.read_csv("sector_etf_prices.csv", index_col="Date", parse_dates=True)

WINDOW = 252  # ~1 trading year
STEP = 5      # slide the window forward 5 trading days at a time (faster, still smooth)

series_a = prices["XLE"]
series_b = prices["XLB"]

rolling_dates = []
rolling_pvalues = []

for start in range(0, len(prices) - WINDOW, STEP):
    end = start + WINDOW
    window_a = series_a.iloc[start:end]
    window_b = series_b.iloc[start:end]

    _, pvalue, _ = coint(window_a, window_b)

    rolling_dates.append(prices.index[end - 1])  # label with the window's last date
    rolling_pvalues.append(pvalue)

rolling_df = pd.DataFrame({"date": rolling_dates, "p_value": rolling_pvalues})
rolling_df.to_csv("xle_xlb_rolling_cointegration.csv", index=False)

pct_reliable = (rolling_df["p_value"] < 0.05).mean() * 100
print(f"\nXLE/XLB was cointegrated (p < 0.05) in {pct_reliable:.1f}% of rolling 1-year windows")

# Plot rolling p-value alongside the price ratio, so we can see WHEN it broke down
fig, (ax1, ax2) = plt.subplots(2, 1, figsize=(10, 8), sharex=True)

ratio = series_a / series_b
ax1.plot(prices.index, ratio.values)
ax1.axhline(ratio.mean(), color="red", linestyle="--", alpha=0.5, label="5yr mean")
ax1.set_title("XLE/XLB price ratio")
ax1.legend()

ax2.plot(rolling_df["date"], rolling_df["p_value"])
ax2.axhline(0.05, color="red", linestyle="--", label="p = 0.05 cutoff")
ax2.set_title("Rolling 1-year cointegration p-value (lower = more reliable)")
ax2.legend()

plt.tight_layout()
plt.savefig("xle_xlb_rolling_cointegration.png", dpi=120)
print("Saved plot to xle_xlb_rolling_cointegration.png")

# ---------------------------------------------------------
# PART B: Test more granular, same-industry pairs
# ---------------------------------------------------------

GRANULAR_PAIRS = [
    ("XOM", "CVX"),  # Exxon vs Chevron — energy majors
    ("JPM", "BAC"),  # JPMorgan vs Bank of America — large banks
    ("HD", "LOW"),   # Home Depot vs Lowe's — home improvement retail
    ("KO", "PEP"),   # Coca-Cola vs PepsiCo — beverages
    ("XOP", "XLE"),  # Oil & gas exploration ETF vs broad energy ETF
]

granular_tickers = sorted(set(t for pair in GRANULAR_PAIRS for t in pair))
print(f"\nPulling data for granular pairs: {granular_tickers}")

granular_raw = yf.download(granular_tickers, period="5y", auto_adjust=True)["Close"]
granular_prices = granular_raw.dropna()
granular_prices.to_csv("granular_pair_prices.csv")

print("\n" + "=" * 60)
print("GRANULAR PAIR COINTEGRATION RESULTS")
print("=" * 60)

granular_results = []
for ticker_a, ticker_b in GRANULAR_PAIRS:
    score, pvalue, _ = coint(granular_prices[ticker_a], granular_prices[ticker_b])
    granular_results.append({
        "pair": f"{ticker_a}/{ticker_b}",
        "p_value": round(pvalue, 4),
        "likely_cointegrated": pvalue < 0.05
    })
    print(f"{ticker_a}/{ticker_b}: p-value = {pvalue:.4f} "
          f"{'<-- COINTEGRATED' if pvalue < 0.05 else ''}")

granular_df = pd.DataFrame(granular_results)
print("\nSummary:")
print(granular_df)

# Plot ratios for the granular pairs too
fig, axes = plt.subplots(len(GRANULAR_PAIRS), 1, figsize=(10, 14))
for ax, (ticker_a, ticker_b) in zip(axes, GRANULAR_PAIRS):
    ratio = granular_prices[ticker_a] / granular_prices[ticker_b]
    ax.plot(ratio.index, ratio.values)
    ax.axhline(ratio.mean(), color="red", linestyle="--", alpha=0.7, label="mean")
    ax.set_title(f"{ticker_a}/{ticker_b} price ratio")
    ax.legend()

plt.tight_layout()
plt.savefig("granular_pair_ratios.png", dpi=120)
print("\nSaved plot to granular_pair_ratios.png")
plt.show()

"""
STEP 2c: Rolling cointegration check on XOP/XLE.

We got burned trusting a single 5-year cointegration test on XLE/XLB (only 13.4%
of rolling windows were actually cointegrated). Before committing to XOP/XLE as
our final pair, let's verify it's stable over time, not just in the aggregate.
"""

import pandas as pd
import numpy as np
from statsmodels.tsa.stattools import coint
import matplotlib.pyplot as plt

print("Loading granular pair price data...")
prices = pd.read_csv("granular_pair_prices.csv", index_col="Date", parse_dates=True)

WINDOW = 252
STEP = 5

series_a = prices["XOP"]
series_b = prices["XLE"]

rolling_dates = []
rolling_pvalues = []

for start in range(0, len(prices) - WINDOW, STEP):
    end = start + WINDOW
    _, pvalue, _ = coint(series_a.iloc[start:end], series_b.iloc[start:end])
    rolling_dates.append(prices.index[end - 1])
    rolling_pvalues.append(pvalue)

rolling_df = pd.DataFrame({"date": rolling_dates, "p_value": rolling_pvalues})
rolling_df.to_csv("xop_xle_rolling_cointegration.csv", index=False)

pct_reliable = (rolling_df["p_value"] < 0.05).mean() * 100
print(f"\nXOP/XLE was cointegrated (p < 0.05) in {pct_reliable:.1f}% of rolling 1-year windows")
print(f"(For comparison, XLE/XLB was only cointegrated 13.4% of the time)")

# Plot ratio + rolling p-value together
fig, (ax1, ax2) = plt.subplots(2, 1, figsize=(10, 8), sharex=True)

ratio = series_a / series_b
ax1.plot(prices.index, ratio.values)
ax1.axhline(ratio.mean(), color="red", linestyle="--", alpha=0.5, label="5yr mean")
ax1.set_title("XOP/XLE price ratio")
ax1.legend()

ax2.plot(rolling_df["date"], rolling_df["p_value"])
ax2.axhline(0.05, color="red", linestyle="--", label="p = 0.05 cutoff")
ax2.set_title("Rolling 1-year cointegration p-value (lower = more reliable)")
ax2.legend()

plt.tight_layout()
plt.savefig("xop_xle_rolling_cointegration.png", dpi=120)
print("Saved plot to xop_xle_rolling_cointegration.png")
plt.show()

"""
STEP 2d: Wide-universe pair screening.

Instead of hand-picking 4-5 pairs and hoping one works, we:
  1. Pull a broad universe of liquid stocks/ETFs across sectors
  2. Test EVERY possible pair combination for cointegration using the most
     recent 1-year window (this tells us what's tradeable RIGHT NOW)
  3. For the top candidates, check their rolling historical stability
     (so we don't repeat the XLE/XLB and XOP/XLE mistake of trusting one
     lucky test)

This mirrors how real pairs trading works: continuously rescan a universe
and only trade pairs that are cointegrated in the current regime.

Run this locally: pip install yfinance statsmodels pandas numpy matplotlib
Note: this takes longer to run since it's testing many more pairs.
"""

import yfinance as yf
import pandas as pd
import numpy as np
from statsmodels.tsa.stattools import coint
from itertools import combinations
import matplotlib.pyplot as plt

# ---------------------------------------------------------
# Universe: liquid large-caps + sector ETFs across several sectors
# ---------------------------------------------------------

UNIVERSE = [
    # Energy
    "XOM", "CVX", "COP", "XLE", "XOP",
    # Financials
    "JPM", "BAC", "WFC", "GS", "XLF",
    # Consumer staples
    "KO", "PEP", "PG", "CL", "XLP",
    # Industrials
    "HON", "UPS", "CAT", "DE", "XLI",
    # Tech
    "MSFT", "AAPL", "ORCL", "CSCO", "XLK",
]

print(f"Universe size: {len(UNIVERSE)} tickers -> {len(list(combinations(UNIVERSE, 2)))} possible pairs")
print("Pulling 5 years of daily data...")

raw = yf.download(UNIVERSE, period="5y", auto_adjust=True)["Close"]
prices = raw.dropna()
prices.to_csv("universe_prices.csv")
print(f"Data shape: {prices.shape[0]} trading days x {prices.shape[1]} tickers")

# ---------------------------------------------------------
# Screen ALL pairs using the most recent 1-year window
# ---------------------------------------------------------

WINDOW = 252
recent_prices = prices.iloc[-WINDOW:]

print(f"\nScreening all pairs using the most recent {WINDOW} trading days...")

screen_results = []
for ticker_a, ticker_b in combinations(UNIVERSE, 2):
    try:
        _, pvalue, _ = coint(recent_prices[ticker_a], recent_prices[ticker_b])
        screen_results.append({
            "pair": f"{ticker_a}/{ticker_b}",
            "ticker_a": ticker_a,
            "ticker_b": ticker_b,
            "p_value": pvalue
        })
    except Exception as e:
        continue

screen_df = pd.DataFrame(screen_results).sort_values("p_value")
screen_df.to_csv("pair_screen_results.csv", index=False)

print(f"\nTotal pairs tested: {len(screen_df)}")
print(f"Currently cointegrated (p < 0.05): {(screen_df['p_value'] < 0.05).sum()}")

print("\nTop 15 most cointegrated pairs right now:")
print(screen_df.head(15).to_string(index=False))

# ---------------------------------------------------------
# For the top 8 candidates, check ROLLING historical stability
# so we don't repeat the earlier mistake of trusting one snapshot
# ---------------------------------------------------------

TOP_N = 8
top_candidates = screen_df.head(TOP_N)

print(f"\n{'=' * 60}")
print(f"CHECKING HISTORICAL STABILITY OF TOP {TOP_N} CANDIDATES")
print(f"{'=' * 60}")

stability_results = []
STEP = 5

for _, row in top_candidates.iterrows():
    ticker_a, ticker_b = row["ticker_a"], row["ticker_b"]
    series_a = prices[ticker_a]
    series_b = prices[ticker_b]

    pvalues = []
    for start in range(0, len(prices) - WINDOW, STEP):
        end = start + WINDOW
        _, pv, _ = coint(series_a.iloc[start:end], series_b.iloc[start:end])
        pvalues.append(pv)

    pct_reliable = (np.array(pvalues) < 0.05).mean() * 100
    stability_results.append({
        "pair": row["pair"],
        "current_p_value": round(row["p_value"], 4),
        "pct_windows_cointegrated": round(pct_reliable, 1)
    })
    print(f"{row['pair']}: currently p={row['p_value']:.4f}, "
          f"historically cointegrated in {pct_reliable:.1f}% of rolling windows")

stability_df = pd.DataFrame(stability_results).sort_values(
    "pct_windows_cointegrated", ascending=False
)
stability_df.to_csv("top_candidates_stability.csv", index=False)

print("\nRanked by historical stability (most reliable first):")
print(stability_df.to_string(index=False))

print("\nDone. Pick the pair with the best combination of current cointegration")
print("AND high historical stability -- that's your final pair for step 3.")

"""
STEP 3: Engineer spread features for JPM/BAC.

Goal: turn the raw price series into features that describe "how unusual is
the current divergence" -- these are what the classifier will eventually
learn from.

We use the LOG spread (log(JPM) - log(BAC)) instead of the raw price ratio.
Why: log spreads behave more symmetrically (a 10% move up and a 10% move down
look the same size in log-space, which isn't true for a raw ratio) and this
is the standard convention in pairs trading literature.

Features built here:
  - spread: log(JPM) - log(BAC)
  - rolling mean / rolling std of the spread (60-day window)
  - z-score: how many standard deviations the spread is from its recent mean
    (this is the core "how extreme is this divergence" signal)
  - rolling volatility of each individual stock (20-day)
  - rolling correlation between JPM and BAC (60-day)
  - days_since_crossing: how many trading days since the spread last crossed
    its own rolling mean (a long stretch without crossing back = warning sign)

Run this locally: pip install pandas numpy matplotlib
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

print("Loading universe price data...")
prices = pd.read_csv("universe_prices.csv", index_col="Date", parse_dates=True)

pair = prices[["JPM", "BAC"]].copy()

# ---------------------------------------------------------
# Core spread + z-score
# ---------------------------------------------------------

pair["log_jpm"] = np.log(pair["JPM"])
pair["log_bac"] = np.log(pair["BAC"])
pair["spread"] = pair["log_jpm"] - pair["log_bac"]

ROLL_WINDOW = 60  # ~3 trading months

pair["spread_mean"] = pair["spread"].rolling(ROLL_WINDOW).mean()
pair["spread_std"] = pair["spread"].rolling(ROLL_WINDOW).std()
pair["zscore"] = (pair["spread"] - pair["spread_mean"]) / pair["spread_std"]

# ---------------------------------------------------------
# Individual stock volatility (20-day rolling std of daily returns)
# ---------------------------------------------------------

VOL_WINDOW = 20

pair["jpm_return"] = pair["JPM"].pct_change()
pair["bac_return"] = pair["BAC"].pct_change()

pair["jpm_volatility"] = pair["jpm_return"].rolling(VOL_WINDOW).std()
pair["bac_volatility"] = pair["bac_return"].rolling(VOL_WINDOW).std()

# ---------------------------------------------------------
# Rolling correlation between the two stocks' returns
# ---------------------------------------------------------

CORR_WINDOW = 60

pair["rolling_correlation"] = pair["jpm_return"].rolling(CORR_WINDOW).corr(
    pair["bac_return"]
)

# ---------------------------------------------------------
# Days since the spread last crossed its own rolling mean
# A long stretch without crossing = the spread has been stuck on one side,
# which is a warning sign that it might not be reverting normally.
# ---------------------------------------------------------

above_mean = (pair["spread"] > pair["spread_mean"]).astype(int)
crossing = above_mean.diff().fillna(0) != 0  # True on days the sign flips

days_since_crossing = []
counter = 0
for crossed in crossing:
    if crossed:
        counter = 0
    else:
        counter += 1
    days_since_crossing.append(counter)

pair["days_since_crossing"] = days_since_crossing

# ---------------------------------------------------------
# Clean up and save
# ---------------------------------------------------------

features = pair.dropna()
features.to_csv("jpm_bac_features.csv")

print(f"\nFeature table shape: {features.shape[0]} rows x {features.shape[1]} columns")
print("\nColumns:", list(features.columns))
print("\nSample rows:")
print(features[["spread", "zscore", "jpm_volatility", "bac_volatility",
                 "rolling_correlation", "days_since_crossing"]].tail(10))

print(f"\nZ-score stats:")
print(features["zscore"].describe())

# ---------------------------------------------------------
# Visualize
# ---------------------------------------------------------

fig, axes = plt.subplots(4, 1, figsize=(11, 12), sharex=True)

axes[0].plot(features.index, features["spread"], label="spread")
axes[0].plot(features.index, features["spread_mean"], color="red",
             linestyle="--", label="rolling mean")
axes[0].set_title("JPM/BAC log spread")
axes[0].legend()

axes[1].plot(features.index, features["zscore"], color="purple")
axes[1].axhline(2, color="red", linestyle="--", alpha=0.6, label="+/- 2 std")
axes[1].axhline(-2, color="red", linestyle="--", alpha=0.6)
axes[1].axhline(0, color="black", linewidth=0.8)
axes[1].set_title("Z-score (how extreme is the current divergence)")
axes[1].legend()

axes[2].plot(features.index, features["rolling_correlation"], color="green")
axes[2].set_title("Rolling 60-day correlation between JPM and BAC returns")

axes[3].plot(features.index, features["days_since_crossing"], color="orange")
axes[3].set_title("Days since spread last crossed its rolling mean")

plt.tight_layout()
plt.savefig("jpm_bac_features.png", dpi=120)
print("\nSaved plot to jpm_bac_features.png")
plt.show()

"""
STEP 4: Label historical divergence events.

An "event" = a moment the z-score crosses beyond +/-2 (the spread becomes
unusually stretched). For each event, we look FORWARD up to N trading days
and ask: did the z-score make it back close to 0 (reverted), or did it stay
stretched / keep diverging the whole window (broke down)?

This label is what the classifier in step 5 will learn to predict.

Two parameters matter a lot here and are worth being deliberate about:
  ENTRY_THRESHOLD = how extreme the z-score must get to count as an "event"
  LOOKAHEAD_DAYS  = how many days we give it to revert before calling it a break
  REVERT_THRESHOLD = how close to 0 counts as "reverted" (doesn't need to be exact)

Run this locally: pip install pandas numpy matplotlib
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

print("Loading feature data...")
features = pd.read_csv("jpm_bac_features.csv", index_col="Date", parse_dates=True)

ENTRY_THRESHOLD = 2.0     # z-score must exceed this (either direction) to count as an event
LOOKAHEAD_DAYS = 20       # ~1 trading month to revert
REVERT_THRESHOLD = 0.5    # z-score must come back within this band to count as "reverted"

zscore = features["zscore"].values
dates = features.index

# ---------------------------------------------------------
# Find divergence events: a day where |z| crosses ABOVE the threshold
# (i.e. the previous day was inside the threshold, today is outside it)
# This avoids counting every single day of an extended divergence as a
# separate event -- we only want the moment it FIRST becomes extreme.
# ---------------------------------------------------------

is_extreme = np.abs(zscore) > ENTRY_THRESHOLD
newly_extreme = is_extreme & ~np.roll(is_extreme, 1)
newly_extreme[0] = False  # ignore the first row (no prior day to compare)

event_indices = np.where(newly_extreme)[0]
print(f"\nFound {len(event_indices)} divergence events (|z| crossing above {ENTRY_THRESHOLD})")

# ---------------------------------------------------------
# For each event, look forward and label revert vs break
# ---------------------------------------------------------

events = []

for idx in event_indices:
    if idx + LOOKAHEAD_DAYS >= len(features):
        continue  # not enough future data to evaluate this event, skip

    entry_zscore = zscore[idx]
    future_window = zscore[idx + 1: idx + 1 + LOOKAHEAD_DAYS]

    # Reverted if the z-score comes back within the revert band at ANY point
    # during the lookahead window
    reverted = np.any(np.abs(future_window) < REVERT_THRESHOLD)

    # Also record how many days it took to revert (NaN if it never did)
    if reverted:
        days_to_revert = np.argmax(np.abs(future_window) < REVERT_THRESHOLD) + 1
    else:
        days_to_revert = np.nan

    event_row = features.iloc[idx].to_dict()
    event_row.update({
        "event_date": dates[idx],
        "entry_zscore": entry_zscore,
        "reverted": int(reverted),
        "days_to_revert": days_to_revert,
    })
    events.append(event_row)

events_df = pd.DataFrame(events).set_index("event_date")
events_df.to_csv("jpm_bac_labeled_events.csv")

# ---------------------------------------------------------
# Summary
# ---------------------------------------------------------

print(f"\nLabeled {len(events_df)} events (skipped events too close to the end of the data)")
print(f"\nClass balance:")
print(events_df["reverted"].value_counts())
print(f"\nReversion rate: {events_df['reverted'].mean() * 100:.1f}%")

print(f"\nAmong reverted events, average days to revert: "
      f"{events_df['days_to_revert'].mean():.1f}")

print("\nSample of labeled events:")
print(events_df[["entry_zscore", "rolling_correlation", "days_since_crossing",
                  "reverted", "days_to_revert"]].head(15))

# ---------------------------------------------------------
# Visualize: spread with reverted events (green) vs broke-down events (red)
# ---------------------------------------------------------

fig, ax = plt.subplots(figsize=(12, 5))
ax.plot(features.index, features["zscore"], color="lightgray", linewidth=0.8, zorder=1)
ax.axhline(ENTRY_THRESHOLD, color="black", linestyle=":", alpha=0.5)
ax.axhline(-ENTRY_THRESHOLD, color="black", linestyle=":", alpha=0.5)

reverted_events = events_df[events_df["reverted"] == 1]
broke_events = events_df[events_df["reverted"] == 0]

ax.scatter(reverted_events.index, reverted_events["entry_zscore"],
           color="green", label=f"Reverted (n={len(reverted_events)})", zorder=2, s=40)
ax.scatter(broke_events.index, broke_events["entry_zscore"],
           color="red", label=f"Broke down (n={len(broke_events)})", zorder=2, s=40)

ax.set_title("JPM/BAC divergence events: reverted vs broke down")
ax.legend()
plt.tight_layout()
plt.savefig("jpm_bac_labeled_events.png", dpi=120)
print("\nSaved plot to jpm_bac_labeled_events.png")
plt.show()